language: go
go:
  - 1.2
install:
  - go get github.com/onsi/gomega
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=profile.cov
  - export PATH=$PATH:$HOME/gopath/bin/
  - goveralls -coverprofile=profile.cov ujwDbhKNAMHPWJD6wu1gHlH7vw6EnSPgA

