language: go
go:
- 1.2

before_install:
- go get github.com/onsi/gomega
- go get code.google.com/p/go.tools/cmd/cover
- go get github.com/mattn/goveralls

env:
  global:
  - secure: NWJjfXUllkkusSLQujaUTHrwW6mRtNVa9y+wxog5X2zWv4/OckAXmA1B26RQ+hJs3ndGRn2V8XGq68N8L1XTD3VeSldmrlk4Y2eHU+EGkhd5+zS70GjeYr0RrxeiqhQ6QV0m4HcFM2iqi1DwUCQQcrln0XmJXZbJX3dQ4AV5YNQ=

script:
- go test -covermode=count -coverprofile=profile.cov
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -repotoken $REPO_TOKEN
