language: go
go:
  - 1.2
before_install:
  - go get github.com/onsi/gomega
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=profile.cov
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -repotoken ujwDbhKNAMHPWJD6wu1gHlH7vw6EnSPgA

